Project_02_Improve/HttpServer/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/6/24 17:06
# @Author  : Zhuxx

from flask import Flask, session, request, redirect, url_for
from Project_02_Improve.HttpServer.views.account import account as account_blueprint
from Project_02_Improve.HttpServer.views.home import home as home_blueprint


def HttpServerApp():
    app = Flask(__name__)                                           #flask实例
    app.jinja_env.auto_reload = True                                #css,js热加载
    app.config['TEMPLATES_AUTO_RELOAD'] = True                      #加载文件热加载
    app.register_blueprint(account_blueprint, url_prefix='/manage') #注册登录蓝图
    app.register_blueprint(home_blueprint)                          #注册主页面蓝图
    app.config.from_object('settings.BasicConfig')                  #加载settings的文件

    @app.before_request
    def check():
        '''
        登陆前验证session
        :return:
        '''
        if (not session.get('user') and not request.path.startswith('/static')
                and request.path != '/manage/login'):
            return redirect(url_for('account.login'))

    @app.template_filter("split_path")
    def split_path(path):
        '''
        目录文件切割
        :param path:
        :return:
        '''
        path_list = path.split('/')
        path_list = [[path_list[i - 1], '/'.join(path_list[:i])] for i in range(1, len(path_list)+1)]
        return path_list

    @app.errorhandler(404)
    def error(error_no):
        '''
        错误信息
        :param error_no:
        :return:
        '''
        return "请使用正确的url访问: /index?"

    return app

Project_02_Improve/HttpServer/views/account.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/6/24 17:06
# @Author  : Zhuxx

from flask import Blueprint, current_app,render_template, request, session, redirect, url_for, jsonify

account = Blueprint('account', __name__)


@account.route('/home')
def home():
    '''
    home页面
    :return:
    '''
    return "<h2>欢迎访问系统主页</h2>"


@account.route('/login', methods=["GET", "POST"])
def login():
    '''
    登录页面，通过js方式进行调用，相关信息参见account.html页面
    :return:
    '''
    if request.method == "GET":
        return render_template('account.html')
    else:
        user = request.form.get('user')
        pwd = request.form.get('pwd')
        user_pwd = current_app.config['USERINFO']
        if user_pwd[user]==pwd and user in user_pwd.keys():               #默认用户名密码
            session['user'] = user
            return jsonify({"code": 200, "error": ""})
        else:
            return jsonify({"code": 401, "error": "用户名或密码错误"})


@account.route('/logout')
def logout():
    '''
    退出登录页面
    :return:
    '''
    del session['user']
    return redirect(url_for('account.login'))

Project_02_Improve/HttpServer/views/dingding.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/7/3 12:56
# @Author  : Zhuxx

import requests

def DDMsg(msg):
    '''
    发送钉钉告警
    :param msg: 钉钉告警信息
    :ps 下面注释的部分为钉钉告警需要@的人的信息，只需要添加电话号码就可以
    :return:
    '''
    url = 'https://oapi.dingtalk.com/robot/send'
    data = {"msgtype": "text","text": {"content": "自动化测试用例遍历结果：{}".format(msg)}}
    response = requests.post(url,json=data)

Project_02_Improve/HttpServer/views/home.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/6/24 17:06
# @Author  : Zhuxx

from flask import Blueprint, render_template, current_app, send_from_directory, request, jsonify,redirect,url_for,session
# from Project_02.HttpServer.views.dingding import DDMsg
import os
import time
import csv
import json
import platform
from collections import defaultdict

home = Blueprint('home', __name__)

scv_global_info = defaultdict(dict)                 #全局数据

class DocumentReader:
    '''
    获取全局的路径并处理路径
    '''
    def __init__(self, real_path):
        self.real_path = real_path   #传入的根路径，为该类的全局路径
        self.data = {
            "code": 0,
            "msg": "",
            "count": 0,
            "data": []
        }                           #基础数据格式
        self.flag = 1               #数据编号
        self.temp = {}              #临时存储深度字典

    def dirs_tree(self,path, depth):
        '''
        用于生成目录格式的树状结构数据
        :param path: 目标路径
        :param depth: 初始深度
        :return:
        '''
        os.chdir(path)
        real_len = len(self.real_path.split('\\')) if platform.system() == "Windows" else len(self.real_path.split('/'))    #获取目标路径长度
        _time = time.strftime("%Y/%m/%d %H:%M", time.localtime(os.path.getctime(path)))                                     #获取文件或文件夹时间
        single_path = '/'.join(path.replace("\\", '/').split('/')[real_len:])                                               #隐藏绝对路径
        #初始根目录
        if depth == 0:
            self.data['data'].append({'authorityId': self.flag, 'authorityName': path.replace('\\','/').split('/')[-1], 'orderNumber': depth,
                   'menuUrl': single_path,'menuIcon': '', 'size': '-','createTime':_time,'authority':'文件夹','isMenu':0,"parentId":-1})
            self.temp[path] = self.flag
            self.flag += 1

        for item in os.listdir(path):
            if os.path.isdir(item) and depth == 0:
                self.data['data'].append({'authorityId': self.flag, 'authorityName': item,
                     'orderNumber': depth + 1, 'menuUrl': single_path,'menuIcon': '', 'size': '-',
                     'createTime':_time,'authority':'文件夹','isMenu':0,"parentId":self.temp[path]})
                self.flag += 1
            elif os.path.isfile(item):
                file_type = os.path.splitext(item)[1].strip('.')
                size = self.get_size(os.path.getsize(item))
                self.data['data'].append({'authorityId': self.flag, 'authorityName': item,
                     'orderNumber': depth, 'menuUrl': single_path,'menuIcon': file_type, 'size': size,
                     'createTime':_time,'authority':'文件','isMenu':1,"parentId":self.temp[path]})
                self.flag += 1
            else:
                self.data['data'].append({'authorityId': self.flag , 'authorityName': item,
                       'orderNumber': depth, 'menuUrl': single_path, 'menuIcon': '', 'size': '-',
                       'createTime': _time, 'authority': '文件夹', 'isMenu': 0, "parentId": self.temp[path]})
                self.flag += 1
            newitem = path + '/' + item                          #拼接目录
            if os.path.isdir(newitem):
                #进入迭代，进行深度遍历
                self.temp[newitem] = self.flag - 1
                self.dirs_tree(newitem, depth + 1)

    def analysis_dir(self):
        '''
        分析目录结构
        :return: 标准的json格式
        '''
        self.dirs_tree(self.real_path,0)
        return self.data

    @staticmethod
    def get_size(size):
        '''
        静态方法，更改文件大小为对应格式
        :param size: 问价大小，为字节
        :return:
        '''
        if size < 1024:
            return '%d  B' % size
        elif 1024 <= size < 1024 * 1024:
            return '%.2f KB' % (size / 1024)
        elif 1024 * 1024 <= size < 1024 * 1024 * 1024:
            return '%.2f MB' % (size / (1024 * 1024))
        else:
            return '%.2f GB' % (size / (1024 * 1024 * 1024))


class ReadFile:

    '''
    读取文件
    '''
    def find_path(self,path,find_str):
        '''
        找到文件路径
        :param path:需要寻找的路径
        :param find_str: 需要寻找的字段
        :return:
        '''
        infos = {}
        for root,_,filenames in os.walk(path):
            for file in filenames:
                msg = self.judge_file(os.path.join(root,file),find_str)
                if msg:
                    infos.setdefault(root.split('\\')[-1],[]).append(msg)
        if infos != {}:
            return list(infos.keys())[0],infos
        else:
            return False

    def judge_file(self,filename,single):
        '''
        判断文件类型
        :param filename:绝对文件路径
        :param single: 寻找的对应标志（ps:寻找字段）
        :return:
        '''
        name,flag = filename.split('.')
        if flag == 'csv':
            return self.find_str(filename,single)
        elif flag in ['xls,xlsx']:
            pass
    
    def find_str(self,filename,flag):
        '''
        寻找特定字段
        :param filename:文件绝对路径
        :param flag: 寻找的对应标志（ps:寻找字段）
        :return:
        '''
        infos = self.read_csv(filename)
        single = []
        for index,value in enumerate(infos):
            if flag == value[2].split('-')[0] and index != 0:
                single.append(index+1)
        if single == []:
            pass
        else:
            return '存在线索的文件为：{}；在以下行中出现：{}'.format(filename.split('\\')[-1],single)

    def deal_info(self,filename):
        '''
        处理字段变成便准字典格式
        :param filename: 文件绝对路径
        :return:
        '''
        title,values = [],[]
        for index,value in enumerate(self.read_csv(filename)):
            if index == 0:
                title = [i.lower().replace(" ","_") for i in value]
            else:
                values.append(value)
        real_info = [dict(zip(title,use)) for use in values]
        return real_info

    def read_csv(self,filename):
        '''
        读取csv文件
        :param filename: 文件绝对路径
        :return:
        '''
        with open(filename,'r') as f:
            reader = csv.reader(f)
            return list(reader)

    def write_scv(self,filename,infos):
        '''
        写入csv文件
        :param filename: 文件绝对路径
        :param infos: 需要写入的信心，格式为：[[1,1,1],[2,2,2]]
        :return:
        '''
        with open(filename,'w',newline='') as f:
            w = csv.writer(f)
            for info in infos:
                w.writerow(info)


@home.route('/index')
def index():
    '''
    页面根目录
    :param path_uri: 根路径
    :return:
    '''
    return render_template('index.html', path='',error_info='')

@home.errorhandler(500)
def error():
    '''
    错误信息页面
    :param error:错误信息
    :return:
    '''
    return render_template('index.html', error_info='哎呀，出错了。')

@home.route('/show_data',methods=['GET','POST'])
def show_data():
    '''
    js获取读取文件数据
    :return:
    '''
    auth = session['user']
    for key,value in scv_global_info[auth].items():
        return jsonify(value)

@home.route('/show_excel')
def show_excel():
    '''
    csv数据展示页面
    :return:
    '''
    path = request.args.get('path') if request.args.get('path') else ""
    filename = request.args.get('filename')
    auth = session['user']
    if path or path == '':
        base_dir = current_app.config['BASEDIR']
        real_path = os.path.join(base_dir,path,filename)
        if scv_global_info[real_path]:
            return render_template('index.html',error_info='{},正在使用该文档，请稍后在进行编辑。'.format(scv_global_info[real_path]),path='')
        else:
            info = ReadFile().deal_info(real_path)
            scv_global_info.setdefault(auth,{})[real_path] = info
            scv_global_info[real_path] = auth
            return render_template('show_excel.html')

@home.route('/save_infos',methods=['POST'])
def save_infos():
    '''
    保存修改后的文件
    :return:
    '''
    model = current_app.config['TITLE']
    use_model = model.split(',')
    save_info = []
    auth = session['user']
    temp_dict = {'Test Summary':'test_summary','Incoming_id':'incoming_id'}
    if request.method == "POST":
        infos = request.get_data()
        values = json.loads(infos)
        for value in values:
            temp = []
            for name in use_model:
                if name in temp_dict:
                    temp.append(value[temp_dict[name]])
                else:
                    temp.append(value[name])
            save_info.append(temp)
    save_info.insert(0,use_model)
    for k,v in scv_global_info[auth].items():
        ReadFile().write_scv(k,save_info)
        scv_global_info[auth][k].pop()
        scv_global_info.pop(k)
    return redirect(url_for('home.index'))

@home.route('/return_local')
def return_local():
    '''
    返回根目录
    :return:
    '''
    scv_global_info.clear()
    return redirect(url_for('home.index'))

@home.route('/search_info',methods=['GET','POST'])
def search_info():
    '''
    查找字段，通过js传回来的字段进行处理，查找
    :return:
    '''
    if request.method == "GET":
        key = request.args.get('key')
        base_dir = current_app.config['BASEDIR']
        read = ReadFile()
        path,msg = read.find_path(base_dir,key)
        # DDMsg(msg)                                                    #钉钉消息发送，需要可以放开注释
        return render_template('index.html',path='', error_info=msg)

@home.route('/get_all_files',methods=['GET','POST'])
def get_file_infos():
    base_dir = current_app.config['BASEDIR']
    file_reader = DocumentReader(base_dir)
    infos = file_reader.analysis_dir()
    return jsonify(infos)

Project_02_Improve/HttpServer/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Report Server</title>
    <link rel="icon" href="{{ url_for('static',filename='img/favicon.ico') }}">
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/signin.css') }}" rel="stylesheet">
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script>
        $(function () {
            $("#submit").click(function (event) {
                event.preventDefault();
                var userInput = $('input[name="user"]');
                var user = userInput.val();
                var pwdInput = $("input[name='pwd']");
                var pwd = pwdInput.val();
                $.post({
                    'url': '/manage/login',
                    'data': {
                        'user': user,
                        'pwd': pwd
                    },
                    "success": function (data) {
                        if (data['code'] == 200) {
                            window.location = '/index'
                        } else {
                            var error = data['error'];
                            $("#error").html(error);
                            $("#error").show();
                        }
                    },
                    'fail': function (error) {
                        consle.log(error)
                    }
                });
            });
        });
    </script>
</head>

<body>

<div class="container">

    <form class="form-signin" method="post">
        <h3 class="form-signin-heading">欢迎访问 Test Case Platform - 测试用例平台</h3>
        <label for="inputName" class="sr-only">用户名</label>
        <input type="text" id="inputName" class="form-control" placeholder="用户名" name="user" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="pwd" required>

        <button class="btn btn-lg btn-primary btn-block" id="submit" type="submit">Login</button>

        <p class="text-danger" style="display:none" id="error"></p>
    </form>

</div>
</body>
</html>

Project_02_Improve/HttpServer/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>您访问的页面不存在</h3>
</body>
</html>

Project_02_Improve/HttpServer/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test Case Platform</title>
    <link rel="icon" href="{{ url_for('static',filename='img/favicon.ico') }}">
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/index.css') }}" rel="stylesheet">
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>

    <link rel="stylesheet" href="../static/assets/layui/css/layui.css">
    <link rel="stylesheet" href="../static/assets/common.css">
    <style>
        input {
            height: 33px;
            line-height: 33px;
            padding: 0 7px;
            border: 1px solid #ccc;
            border-radius: 2px;
            margin-bottom: -2px;
            outline: none;
        }

        input:focus {
            border-color: #009E94;
        }
    </style>
</head>
<body>
<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <div class="navbar-brand">
                Test Case Platform
            </div>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('account.logout') }}">退出</a></li>
        </ul>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">
                    请选择所需上传的本地文件
                </h4>
            </div>
            <div class="modal-body">
                <form id="upload-form" enctype="multipart/form-data">
                    <input id='file' class="btn btn-info" name="upload_file" type="file">
                </form>
            </div>
            <div class="modal-footer">
                <button id='upload' class="btn btn-primary ">上传</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <input type="text" class="input-text" style="width: 250px" placeholder="搜索的条件" id="search_key" name="search_key">
        <button type="submit" class="but but-success" id="do_search" name="do_search">
            搜索线索
        </button>
    </div>
    {% if error_info %}
    <p class="text-danger" id="error">{{ error_info }}</p>
    {% endif %}
</div>

<div class="layui-container">
    <br><br>
    <div class="layui-btn-group">
        <button class="layui-btn" id="btn-expand">全部展开</button>
        <button class="layui-btn" id="btn-fold">全部折叠</button>
    </div>
    &nbsp;&nbsp;
    <input id="edt-search" type="text" placeholder="输入关键字" style="width: 120px;">&nbsp;&nbsp;
    <button class="layui-btn" id="btn-search">&nbsp;&nbsp;搜索&nbsp;&nbsp;</button>

    <table id="auth-table" class="layui-table" lay-filter="auth-table"></table>
</div>

<script type="text/html" id="oper-col">
    <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="look" >查看</a>
</script>

<script>
    $('#upload').click(function () {
        var upload_path = {{path|tojson|safe}};
        var formData = new FormData($('#upload-form')[0]);
        formData.append("upload_path", upload_path);
        $.post({
            url: '/upload',
            dataType: 'json',
            type: 'POST',
            data: formData,
            async: true,
            cashe: false,
            contentType: false,
            processData: false,
            success: function (returndata) {
                if(returndata['code'] == 200){
                    var info = returndata['info'];
                    alert(info);
                }
            },
            error: function (returndata) {
                alert("上传失败！")
            }
        })
    });
</script>

<script type="text/javascript">
    /*搜索*/
    $(document).ready(function () {
        $("#do_search").click(function(){
         var key=$("#search_key").val();
           location.href="{{url_for('home.search_info')}}?key="+key;
        });
    });
</script>

<script src="../static/assets/layui/layui.js"></script>
<script>
    layui.config({
        base: '../static/module/'
    }).extend({
        treetable: 'treetable-lay/treetable'
    }).use(['table', 'treetable'], function () {
        var $ = layui.jquery;
        var table = layui.table;
        var treetable = layui.treetable;

        // 渲染表格
        layer.load(2);
        treetable.render({
            treeColIndex: 1,
            treeSpid: -1,
            treeIdName: 'authorityId',
            treePidName: 'parentId',
            elem: '#auth-table',
            url:"{{url_for('home.get_file_infos')}}",
            page: false,
            cols: [[
                {type: 'numbers',title:'编号'},
                {field: 'authorityName', minWidth: 300, title: '目录名称'},
                {field: 'size', width: 150,title: '文件大小',align: 'center'},
                {field: 'menuIcon', width: 100,title: '文件后缀',align: 'center'},
                {field: 'authority', width: 150,title: '文件类型',align: 'center'},
                {
                    field: 'isMenu', width: 80, align: 'center', templet: function (d) {
                        if (d.isMenu == 1) {
                            return '<span class="layui-badge layui-bg-gray">文件</span>';
                        }
                        if (d.parentId == -1) {
                            return '<span class="layui-badge layui-bg-blue">根目录</span>';
                        } else {
                            return '<span class="layui-badge-rim">文件夹</span>';
                        }
                    }, title: '类型'
                },
                {field:'createTime',width:150,title:'创建时间'},
                {field:'isMenu',width:80,templet:function (d) {
                    if (d.isMenu==1){
                        table.on('tool(auth-table)',function (obj) {
                            var data = obj.data;
                            var layEvent = obj.event;
                            if (layEvent === 'look'){
                                location.href = "{{url_for('home.show_excel')}}?" +"path=" + data.menuUrl + "&filename=" + data.authorityName;
                            }
                        });
                        return '<a class="layui-btn layui-btn-primary layui-btn-xs layui-bg-blue" lay-event="look" >查看</a>'
                    } else {
                        return ''
                    }
                    },title:'功能',align:'center'}
            ]],
            done: function () {
                layer.closeAll('loading');
            }
        });

        $('#btn-expand').click(function () {
            treetable.expandAll('#auth-table');
        });

        $('#btn-fold').click(function () {
            treetable.foldAll('#auth-table');
        });

        $('#btn-search').click(function () {
            var keyword = $('#edt-search').val();
            var searchCount = 0;
            $('#auth-table').next('.treeTable').find('.layui-table-body tbody tr td').each(function () {
                $(this).css('background-color', 'transparent');
                var text = $(this).text();
                if (keyword != '' && text.indexOf(keyword) >= 0) {
                    $(this).css('background-color', 'rgba(250,230,160,0.5)');
                    if (searchCount == 0) {
                        treetable.expandAll('#auth-table');
                        $('html,body').stop(true);
                        $('html,body').animate({scrollTop: $(this).offset().top - 150}, 500);
                    }
                    searchCount++;
                }
            });
            if (keyword == '') {
                layer.msg("请输入搜索内容", {icon: 5});
            } else if (searchCount == 0) {
                layer.msg("没有匹配结果", {icon: 5});
            }
        });
    });
</script>
</body>
</html>

Project_02_Improve/HttpServer/templates/show_excel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report Server</title>
    <link rel="icon" href="{{ url_for('static',filename='img/favicon.ico') }}">
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/index.css') }}" rel="stylesheet">
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>

    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap-table.min.css" />
    <script src="../static/js/bootstrap-table.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="../static/js/bootstrap-table-zh-CN.min.js" type="text/javascript" charset="utf-8"></script>


</head>
<body>
<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <div class="navbar-brand">
                Report Server
            </div>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('home.index') }}">首页</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('account.logout') }}">退出</a></li>
        </ul>
    </div>
</div>


<div class="table-box" style="margin: 20px;">
    <div class="row">
        <a href="{{url_for('home.return_local')}}">返回目录</a>
    </div>
    <div id="toolbar">
        <button id="button" class="btn btn-default">新增一行</button>
        <button id="getTableData" class="btn btn-default">提交数据</button>
        <button id="remove" class="btn btn-default">删除</button>
    </div>
    <table id="table"></table>
</div>


<script type="text/javascript">
    $(function() {
    let $table = $('#table');
    let $button = $('#button');
    let $getTableData = $('#getTableData');
    let $remove = $('#remove');

    $remove.click(function () {
        var idlist = $('#table').bootstrapTable('getAllSelections');
        var check_value = [];
        for (var i = 0; i < idlist.length; i++) {
            check_value.push(idlist[i].test_id);
        }
        if (check_value.length == 0){
            alert('请先选择要删除的记录!');
            return;
        } else {
            alert("请再次确认你删除的用例标号:[" + check_value + "]");
            $table.bootstrapTable('remove',{
                    field: 'test_id',
                    values: check_value
                })
        }
    });

    $button.click(function() {
        var idlist = $('#table').bootstrapTable('getAllSelections');
        var check_value = [];
        var rows = {
                test_id: '',
                test_summary:"",
                test_describe: '',
                test_priorityh: '',
                test_flag: '',
                test_mothed: '',
                path: '',
                incoming_id:'',
                data: '',
                expected_result: '',
                actual_result: '',
                test_result: ''
            };

        for (var i = 0; i < idlist.length; i++) {
            check_value.push(idlist[i].test_id);
        }
        $table.bootstrapTable('insertRow', {
            index: check_value[0],
            row: rows,
        });
    });

    $table.bootstrapTable({
        url:"{{url_for('home.show_data')}}",
        toolbar: '#toolbar',
        clickEdit: true,
        showToggle: true,
        pagination: true,
        showColumns: true,
        showPaginationSwitch: true,
        showRefresh: true,
        clickToSelect: true,
        columns: [{
            checkbox: true
        }, {
            field: 'test_id',
            title: '用例编号'
        }, {
            field:'test_summary',
            title:'Test Summary'
        },{
            field: 'test_describe',
            title: '用例描述'
        }, {
            field: 'test_priorityh',
            title: 'Test Priorityh'
        }, {
            field: 'test_flag',
            title: 'Test Flag'
        }, {
            field: 'test_mothed',
            title: 'Test Method'
        }, {
            field: 'incoming_id',
            title: 'Incoming ID'
        },{
            field: 'path',
            title: 'Test Path'
        }, {
            field: 'data',
            title: 'Test Data'
        }, {
            field: 'expected_result',
            title: 'Expected Result'
        }, {
            field: 'actual_result',
            title: 'Actual Result'
        }, {
            field: 'test_result',
            title: 'Test Result'
        }, ],
        /**
         * @param {点击列的 field 名称} field
         * @param {点击列的 value 值} value
         * @param {点击列的整行数据} row
         * @param {td 元素} $element
         */
        onClickCell: function(field, value, row, $element) {
            $element.attr('contenteditable', true);
            $element.blur(function() {
                let index = $element.parent().data('index');
                let tdValue = $element.html();
                saveData(index, field, tdValue);
            })
        }
    });

    $getTableData.click(function() {
        alert(JSON.stringify($table.bootstrapTable('getData')));
        var value = JSON.stringify($table.bootstrapTable('getData'));
        var httpRequest = new XMLHttpRequest();
        httpRequest.open('POST',"save_infos",true);
        httpRequest.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        httpRequest.send(value);

        httpRequest.onreadystatechange = function(){
            if (httpRequest.status == 200) {
                var json = httpRequest.responseText;
                window.location.href = "{{url_for('home.index')}}";
                console.log(json)
            }
        };
    });

    function saveData(index, field, value) {
        $table.bootstrapTable('updateCell', {
            index: index,
            field: field,
            value: value
        })
    }
});
</script>
</body>
</html>